# KNN Implementation without Using scikit learn-Library

In [85]:
########### KNN Implementation without Using scikit learn Library
f=open("C:/Users/truna/Downloads/IRIS (2).csv")
#print(f.read())                                                                                                      

In [86]:
#### Split the data
list_a=[]
list_b=[]
list_c=[]
list_d=[]
list_label=[]
counter=0
for line in f:
    if counter!=0:
        data=line.split(",")
        list_a.append(float(data[0]))
        list_b.append(float(data[1]))
        list_c.append(float(data[2]))
        list_d.append(float(data[3]))
        list_label.append(data[4])
    else:
        counter+=1
        

In [87]:
print(list_a)

[5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.8, 4.8, 4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5.0, 5.0, 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5.0, 5.5, 4.9, 4.4, 5.1, 5.0, 4.5, 4.4, 5.0, 5.1, 4.8, 5.1, 4.6, 5.3, 5.0, 7.0, 6.4, 6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5.0, 5.9, 6.0, 6.1, 5.6, 6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7, 6.0, 5.7, 5.5, 5.5, 5.8, 6.0, 5.4, 6.0, 6.7, 6.3, 5.6, 5.5, 5.5, 6.1, 5.8, 5.0, 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5, 7.7, 7.7, 6.0, 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2, 7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6.0, 6.9, 6.7, 6.9, 5.8, 6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9]


In [88]:
list_b

[3.5,
 3.0,
 3.2,
 3.1,
 3.6,
 3.9,
 3.4,
 3.4,
 2.9,
 3.1,
 3.7,
 3.4,
 3.0,
 3.0,
 4.0,
 4.4,
 3.9,
 3.5,
 3.8,
 3.8,
 3.4,
 3.7,
 3.6,
 3.3,
 3.4,
 3.0,
 3.4,
 3.5,
 3.4,
 3.2,
 3.1,
 3.4,
 4.1,
 4.2,
 3.1,
 3.2,
 3.5,
 3.1,
 3.0,
 3.4,
 3.5,
 2.3,
 3.2,
 3.5,
 3.8,
 3.0,
 3.8,
 3.2,
 3.7,
 3.3,
 3.2,
 3.2,
 3.1,
 2.3,
 2.8,
 2.8,
 3.3,
 2.4,
 2.9,
 2.7,
 2.0,
 3.0,
 2.2,
 2.9,
 2.9,
 3.1,
 3.0,
 2.7,
 2.2,
 2.5,
 3.2,
 2.8,
 2.5,
 2.8,
 2.9,
 3.0,
 2.8,
 3.0,
 2.9,
 2.6,
 2.4,
 2.4,
 2.7,
 2.7,
 3.0,
 3.4,
 3.1,
 2.3,
 3.0,
 2.5,
 2.6,
 3.0,
 2.6,
 2.3,
 2.7,
 3.0,
 2.9,
 2.9,
 2.5,
 2.8,
 3.3,
 2.7,
 3.0,
 2.9,
 3.0,
 3.0,
 2.5,
 2.9,
 2.5,
 3.6,
 3.2,
 2.7,
 3.0,
 2.5,
 2.8,
 3.2,
 3.0,
 3.8,
 2.6,
 2.2,
 3.2,
 2.8,
 2.8,
 2.7,
 3.3,
 3.2,
 2.8,
 3.0,
 2.8,
 3.0,
 2.8,
 3.8,
 2.8,
 2.8,
 2.6,
 3.0,
 3.4,
 3.1,
 3.0,
 3.1,
 3.1,
 3.1,
 2.7,
 3.2,
 3.3,
 3.0,
 2.5,
 3.0,
 3.4,
 3.0]

In [89]:
list_label

['Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-setosa\n',
 'Iris-versicolor\n',
 'Iris-versicolor\n',
 'Iris-versicolor\n',
 'Iris-versicolor\n',
 'Iris-versi

### Train Test split 

In [90]:
### train test data
#### store the train data
train_a=[]
train_b=[]
train_c=[]
train_d=[]
train_label=[]
test_a=[]
test_b=[]
test_c=[]
test_d=[]
test_label=[]
train_size=int(0.8*len(list_a))
train_a=list_a[0:train_size]
train_b=list_b[0:train_size]
train_c=list_c[0:train_size]
train_d=list_d[0:train_size]
train_label=list_label[0:train_size]
#### To store the test data
test_a=list_a[train_size:]
test_b=list_b[train_size:]
test_c=list_c[train_size:]
test_d=list_d[train_size:]
test_label=list_label[train_size:]

In [91]:
print(len(train_a))
print(len(train_b))
print(len(train_c))
print(len(train_d))
print(len(train_label))

120
120
120
120
120


In [92]:
print(len(test_a))
print(len(test_b))
print(len(test_c))
print(len(test_d))
print(len(test_label))

30
30
30
30
30


In [93]:
test_label

['Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n']

### Predict the label for test data 

In [94]:
### knn classifier
def knn_classifier(k,train_a,train_b,train_c,train_d,test_a,test_b,test_c,test_d,train_label):
    new_class=[]
    for i in range(len(test_a)):
        dist=[]
        for j in range(len(train_a)):
            dist.append((train_a[j]-test_a[i])**2+(train_b[j]-test_b[i])**2+(train_c[j]-test_c[i])**2+(train_d[j]-test_d[i])**2)
    
        class_list=[]
        for z in sorted(dist)[0:k]:
            class_list.append(train_label[dist.index(z)])
        new_class.append(max(set(class_list),key=class_list.count))      
    return(new_class)
    

In [95]:
k=5
knn_classifier(k,train_a,train_b,train_c,train_d,test_a,test_b,test_c,test_d,train_label)

['Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-versicolor\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-versicolor\n',
 'Iris-versicolor\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-versicolor\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-versicolor\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-virginica\n',
 'Iris-versicolor\n']

In [96]:
testnewclass=knn_classifier(k,train_a,train_b,train_c,train_d,test_a,test_b,test_c,test_d,train_label)
trainnewclass=knn_classifier(k,train_a,train_b,train_c,train_d,train_a,train_b,train_c,train_d,train_label)

In [97]:
#### tabular form
for a,b,c,d,e,f,g in zip(list(range(1,len(testnewclass)+1)), test_a,test_b,test_c,test_d,test_label,testnewclass):
    print(a,b,c,d,e,f,g)

1 6.9 3.2 5.7 2.3 Iris-virginica
 Iris-virginica

2 5.6 2.8 4.9 2.0 Iris-virginica
 Iris-virginica

3 7.7 2.8 6.7 2.0 Iris-virginica
 Iris-virginica

4 6.3 2.7 4.9 1.8 Iris-virginica
 Iris-versicolor

5 6.7 3.3 5.7 2.1 Iris-virginica
 Iris-virginica

6 7.2 3.2 6.0 1.8 Iris-virginica
 Iris-virginica

7 6.2 2.8 4.8 1.8 Iris-virginica
 Iris-versicolor

8 6.1 3.0 4.9 1.8 Iris-virginica
 Iris-versicolor

9 6.4 2.8 5.6 2.1 Iris-virginica
 Iris-virginica

10 7.2 3.0 5.8 1.6 Iris-virginica
 Iris-virginica

11 7.4 2.8 6.1 1.9 Iris-virginica
 Iris-virginica

12 7.9 3.8 6.4 2.0 Iris-virginica
 Iris-virginica

13 6.4 2.8 5.6 2.2 Iris-virginica
 Iris-virginica

14 6.3 2.8 5.1 1.5 Iris-virginica
 Iris-versicolor

15 6.1 2.6 5.6 1.4 Iris-virginica
 Iris-virginica

16 7.7 3.0 6.1 2.3 Iris-virginica
 Iris-virginica

17 6.3 3.4 5.6 2.4 Iris-virginica
 Iris-virginica

18 6.4 3.1 5.5 1.8 Iris-virginica
 Iris-virginica

19 6.0 3.0 4.8 1.8 Iris-virginica
 Iris-versicolor

20 6.9 3.1 5.4 2.1 Iris-virginica
 

### Find train and test error 

In [98]:
###### train and test error
test_neg=0
for i in range(len(testnewclass)):
    if(test_label[i]!=testnewclass[i]):
        test_neg += 1

train_neg=0
for i in range(len(trainnewclass)):
    if(train_label[i]!=trainnewclass[i]):
        train_neg += 1
print("test error: ",round((test_neg/len(testnewclass)),3))               #### for upto 3 decimal point
print("train error: ",round((train_neg/len(trainnewclass)),3))


test error:  0.2
train error:  0.017


# K-Nearest Neighbors (K-NN)  Using Scikit-Learn

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt   
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv("C:/Users/truna/Downloads/IRIS (2).csv")
X = dataset.iloc[:, :-1].values        
y = dataset.iloc[:, -1].values   


## Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [8]:
print(X_train)

[[5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.8 3.  5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]
 [5.  3.5 1.6 0.6]
 [5.4 3.7 1.5 0.2]
 [5.  2.  3.5 1. ]
 [6.5 3.  5.5 1.8]
 [6.7 3.3 5.7 2.5]
 [6.  2.2 5.  1.5]
 [6.7 2.5 5.8 1.8]
 [5.6 2.5 3.9 1.1]
 [7.7 3.  6.1 2.3]
 [6.3 3.3 4.7 1.6]
 [5.5 2.4 3.8 1.1]
 [6.3 2.7 4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [4.9 2.5 4.5 1.7]
 [6.3 2.5 5.  1.9]
 [7.  3.2 4.7 1.4]
 [6.5 3.  5.2 2. ]
 [6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [5.5 2.5 4.  1.3]
 [6.1 3.  4.6 1.4]
 [7.2 3.2 6.  1.8]
 [5.3 3.7 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [6.4 2.7 5.3 1.9]
 [5.7 3.  4.2 1.2]
 [5.4 3.4 1.7 0.2]
 [5.7 4.4 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [4.6 3.1 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [4.6 3.4 1.4 0.3]
 [6.2 2.2 4.5 1.5]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [4.8 3.  1.4 0.1]
 [7.1 3.  5.9 2.1]
 [6.9 3.2 5.7 2.3]
 [6.5 3.  5.8 2.2]
 [6.4 2.8 5.6 2.1]
 [5.1 3.8 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [6.5 3.2 5.1 2. ]
 [6.7 3.3 5.

In [9]:
print(y_train)

['Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'

In [10]:
print(X_test)

[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 1.5]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 1.5]
 [6.1 2.8 4.7 1.2]
 [6.5 2.8 4.6 1.5]
 [6.1 2.9 4.7 1.4]
 [4.9 3.1 1.5 0.1]
 [6.  2.9 4.5 1.5]
 [5.5 2.6 4.4 1.2]
 [4.8 3.  1.4 0.3]
 [5.4 3.9 1.3 0.4]
 [5.6 2.8 4.9 2. ]
 [5.6 3.  4.5 1.5]
 [4.8 3.4 1.9 0.2]
 [4.4 2.9 1.4 0.2]
 [6.2 2.8 4.8 1.8]
 [4.6 3.6 1.  0.2]
 [5.1 3.8 1.9 0.4]
 [6.2 2.9 4.3 1.3]
 [5.  2.3 3.3 1. ]
 [5.  3.4 1.6 0.4]
 [6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.2]
 [5.2 2.7 3.9 1.4]
 [5.7 3.8 1.7 0.3]
 [6.  2.7 5.1 1.6]]


In [11]:
print(y_test)

['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor']


## Feature Scaling

In [12]:
##### Perform Feature scaling to bring the dta on same scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
print(X_train)

[[ 1.54399532e-02 -1.19254753e-01  2.25126850e-01  3.56381749e-01]
 [-9.98450310e-02 -1.04039491e+00  1.13559562e-01 -2.86480506e-02]
 [ 1.05300481e+00 -1.19254753e-01  9.50314227e-01  1.12644135e+00]
 [-1.36797986e+00  3.41315328e-01 -1.39259884e+00 -1.31208072e+00]
 [ 1.16828980e+00  1.11030287e-01  7.27179649e-01  1.38312788e+00]
 [-1.02212490e+00  1.03217045e+00 -1.22524790e+00 -7.98707650e-01]
 [-5.60984968e-01  1.49274053e+00 -1.28103155e+00 -1.31208072e+00]
 [-1.02212490e+00 -2.42210516e+00 -1.65358660e-01 -2.85334584e-01]
 [ 7.07149859e-01 -1.19254753e-01  9.50314227e-01  7.41411549e-01]
 [ 9.37719827e-01  5.71600368e-01  1.06188152e+00  1.63981441e+00]
 [ 1.30724937e-01 -1.96153508e+00  6.71396005e-01  3.56381749e-01]
 [ 9.37719827e-01 -1.27067995e+00  1.11766516e+00  7.41411549e-01]
 [-3.30414999e-01 -1.27067995e+00  5.77759173e-02 -1.56991317e-01]
 [ 2.09056967e+00 -1.19254753e-01  1.28501609e+00  1.38312788e+00]
 [ 4.76579890e-01  5.71600368e-01  5.04045072e-01  4.84725016e

In [14]:
print(X_test)

[[-0.09984503 -0.57982483  0.72717965  1.51147115]
 [ 0.13072494 -1.96153508  0.11355956 -0.28533458]
 [-0.44569998  2.64416573 -1.33681519 -1.31208072]
 [ 1.62942973 -0.34953979  1.39658338  0.74141155]
 [-1.0221249   0.80188541 -1.28103155 -1.31208072]
 [ 0.47657989  0.57160037  1.22923245  1.63981441]
 [-1.0221249   1.03217045 -1.39259884 -1.18373745]
 [ 0.93771983  0.11103029  0.50404507  0.35638175]
 [ 1.05300481 -0.57982483  0.55982872  0.22803848]
 [ 0.24600992 -0.57982483  0.11355956  0.09969522]
 [ 0.24600992 -1.04039491  1.00609787  0.22803848]
 [ 0.59186487  0.34131533  0.39247778  0.35638175]
 [ 0.24600992 -0.57982483  0.50404507 -0.02864805]
 [ 0.70714986 -0.57982483  0.44826143  0.35638175]
 [ 0.24600992 -0.34953979  0.50404507  0.22803848]
 [-1.13740989  0.11103029 -1.28103155 -1.44042398]
 [ 0.13072494 -0.34953979  0.39247778  0.35638175]
 [-0.44569998 -1.04039491  0.33669414 -0.02864805]
 [-1.25269487 -0.11925475 -1.33681519 -1.18373745]
 [-0.56098497  1.95331061 -1.39

## Training the K-NN model on the Training set

In [15]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

## Predicting a new result

In [16]:
print(classifier.predict(sc.transform([[5.1,3.5,1.4,0.2]])))

['Iris-setosa']


## Predicting the Test set results

In [17]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']


## Making the Confusion Matrix

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


0.9736842105263158